### ISSUE TITLE
False external links broken reported.

### ISSUE THREAD

**Issue by Raza403** [fulldecent/github-pages-template#62]
Some links are not broken but are reported as broken by our external link checker.
For example, the link https://twitter.com/aclstraining is not broken but reported as broken always.
Here is the [build](https://github.com/fulldecent/mtssites/actions/runs/7237173624/job/19716501455#step:8:21).

**Comment by fulldecent** [comment]
Per Raza: a way to improve this is to have the test case report the HTTP error code. Did it fail to connect or is there a 404/40x error?

**Comment by fulldecent** [comment]
Also, the root cause is maybe that our IP address is getting blocked because of frequent checking. We want to make sure that our cache is working.

Something else to do is when the test case is started to report about the cache:

> Loaded link checker cache: 321 items, newest 2024-03-04, oldest 2023-12-13

For example that can go here https://github.com/fulldecent/mtssites/actions/runs/8297750824/job/22709517969#step:8:14

**Comment by Raza403** [comment]
There are chances that the IP address used by GitHub actions is blocked, but I have tried this on a new IP on a new machine, I got the same result. One problem is most of these websites are blocking `curl` request, so I upgraded the curl request to look more legit and it worked on 80% of the sites previously giving false broken link errors.
Here is the updated curl command i used
```bash
curl --head --silent --fail --max-time 5 --location \
--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.9999.999 Safari/537.36" \
--header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" \
"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3116747/"```

**Comment by fulldecent** [comment]
Nice, good to use those changes

**Comment by Raza403** [comment]
Deployed the updated on all the sites.

**Comment by fulldecent** [comment]
Cool. 

Can you please also capture the issue: to test and confirm that link cache is working. This can go in the upstream repo

**Comment by Raza403** [comment]
How will I do it, one way I could think of is updating the message to `external link is broken and saved in the cache` in the following code, this way we could be sure that link is cached.
```js
const row = this.db.prepare("SELECT found, time FROM urls WHERE url = ?").get(url);
    if (row) {
      // Link is bad, from recent cache
      if (row.found === 0) {
        this.report({
          node: element,
          message: `external link is broken: ${url}`,
        });
      }
      return;
    }
```
